# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test_Kayitol():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_kayit_ol(self):
    self.driver.get("https://tobeto.com/giris")
    self.driver.maximize_window()
    self.driver.execute_script("window.scrollTo(0,250)") 
    element = self.driver.find_element(By.XPATH, "/html/body/div[1]/div/main/section/div/div/div[1]/div/div[2]/label/small/a")
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    self.driver.execute_script("window.scrollTo(0,300)") 
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.XPATH, "/html/body/div[1]/div/main/section/div/div/div[1]/div/div[2]/label/small/a")))
    self.driver.find_element(By.XPATH, "/html/body/div[1]/div/main/section/div/div/div[1]/div/div[2]/label/small/a").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.NAME, "firstName")))
    self.driver.find_element(By.NAME, "firstName").send_keys("eda")
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.NAME, "lastName")))
    self.driver.find_element(By.NAME, "lastName").send_keys("sarı")
    self.driver.execute_script("window.scrollTo(0,300)") 
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("e")
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.XPATH, "/html/body/div[1]/div/main/section/div/div/div[1]/div/div/form/p")))
    assert self.driver.find_element(By.XPATH, "/html/body/div[1]/div/main/section/div/div/div[1]/div/div/form/p").text == "Geçersiz e-posta adresi*"
    

  
